### PR TITLE
Attributes.md

### PR DESCRIPTION
**Pull request by Reamuji**
Tiananmen Sguares

### CODE REVIEW

**Comment by SpeckyYT** [comment]
Bro, those are compile flags, not tags ://

**Comment by Reamuji** [comment]
nope they are different thing
even if it's not called tags, it must be called attributes
main.rs line 164 : 
```rs
let tags = notes.tag.tags.iter();
for tag in tags {
    match tag.0.as_str() {
        "console_output" => gd_enabled = false,
        "no_level" => {
            gd_enabled = false;
            compile_only = true;
        }
        _ => (),
    }
}
```
compiler.rs line 91 & 1491: 
```rs
if !notes.tag.tags.iter().any(|x| x.0 == "no_std") {
. . .
let save_value = notes.tag.tags.iter().any(|x| x.0 == "cache_output");```

**Comment by Reamuji** [comment]
Changed the name to attributes

**Comment by Spu7Nix** [comment]
is this ready to be merged?

**Pull request merged**
