### PR TITLE
Dumbasses didn't escape the char

### PR DESCRIPTION
**Pull request by Reamuji**
Whats 9+10

### CODE REVIEW

**Comment by Megarion** [comment]
19 💀

**Comment by feverdreme** [comment]
i want to know what monster thought it was ok to use angle brackets like that in the documentation. anything resembling XML has no place here

**Comment by Spu7Nix** [comment]
why did you only escape the first 6 angle brackets

**Comment by Reamuji** [comment]
Lazyness lmao
Wait imma do it real quick

**Pull request merged**
