### PR TITLE
Tags.md (help me xd)

### PR DESCRIPTION
**Pull request by Reamuji**
Job available
Docs writer
apply today

### CODE REVIEW

**Comment by zTags** [comment]
TAGS.MD

**Comment by Spu7Nix** [comment]
You should add this file to the sidebar so it can be accessed on the website :)

**Comment by Reamuji** [comment]
Actually im planing to do that after it's written properly

Well it's ok ig ill add a note instead

**Comment by Reamuji** [comment]
Uhh, looks like i can't do it rn. Maybe later

**Pull request closed without merging**
