### PR TITLE
bruh wtf sput how could you mess this up its just a simple 11 letter sentence how could you make 3 grammatical mistakes in a simple 11 letter sentence, you keep shocking me please dont repeat this mistake ever again

### PR DESCRIPTION
**Pull request by Fl1pNatic**

### CODE REVIEW

**Review by SpeckyYT — APPROVED** [review]
stun amogus

**Comment by Spu7Nix** [comment]
you wouldn't understand

**Comment by Reamuji** [comment]
next pgae

**Comment by Deltara3** [comment]
> you wouldn't understand

i agree

**Comment by zTags** [comment]
image
me after understanding

**Comment by SpeckyYT** [comment]
> image
> me after understanding

same

**Comment by Fl1pNatic** [comment]
> > image
> > me after understanding
> 
> same

same

**Comment by feverdreme** [comment]
> > > image
> > > me after understanding
> > 
> > 
> > same
> 
> same

same

**Comment by Darkar25** [comment]
> > > > image
> > > > me after understanding
> > > 
> > > 
> > > same
> > 
> > 
> > same
> 
> same

same

**Pull request closed without merging**
