### PR TITLE
Add next page button, builtin type member , range.md and more typo

### PR DESCRIPTION
**Pull request by Reamuji**
Idk what to fill in the 'value' since its written in rust. So i emit it

### CODE REVIEW

**Comment by Reamuji** [comment]
Wait, fuck there's an unintended typo

**Comment by Spu7Nix** [comment]
as opposed to all the intended typos

**Comment by Reamuji** [comment]
No one can fix the typo that was chosen for them. All that remains is the result, where you will all not comprehend. Eternal typo only exists only within 3context-splitting.md. Sing a song of sorrow in a world where correct spelling has vanished.

**Comment by Reamuji** [comment]
Actually the intended typo is only "next pgae" below comig soom

**Pull request merged**
