### PR TITLE
Fix $.random()

### PR DESCRIPTION
**Pull request by pundang**
ye fuck dis

### CODE REVIEW

**Comment by Unzor** [comment]
real

**Comment by itsmebombie** [comment]
unzor deez muts

**Comment by Unzor** [comment]
not real

**Comment by kr8gz** [comment]
like your bitches

**Comment by Unzor** [comment]
thanks

**Comment by Spu7Nix** [comment]
these docs are auto genereated, please change the corresponding text in [SPWN-language](https://github.com/Spu7Nix/SPWN-language) instead (in [this file](https://github.com/Spu7Nix/SPWN-language/blob/master/compiler/src/builtins.rs))

**Pull request closed without merging**
